name: PUBLISH

on:
  workflow_run:
    workflows: [BUILD_LINT_TEST]
    types: [completed]
  push:
    branches: [main]

jobs:
  publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: Release
        uses: justincy/github-action-npm-release@2.0.1
        id: release
      - name: publish
        if: ${{ steps.release.outputs.released == 'true' }}
        run: npm install && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
